........F.F
======================================================================
FAIL: test_size_some_larger_perms_exact_match (__main__.TestCountLarge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a1/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '0' != '1'
- 0
+ 1


======================================================================
FAIL: test_size_some_larger_perms_relaxed_match (__main__.TestCountLarge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a1/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '0' != '2'
- 0
+ 2


----------------------------------------------------------------------
Ran 11 tests in 0.055s

FAILED (failures=2)
